apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
spec:
  storageClassName: mongodb-storage  # Use the name of the StorageClass you created
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Specify the desired storage size
